### ISSUE TITLE
GraphQL config: database endpoint is wrong

### ISSUE THREAD

**Issue by mkozhukharenko** [graphql-boilerplates/node-graphql-server#62]
### Current behaviour:

current graphql config yaml is:
```
projects:
  app:
    ...
  database:
    schemaPath: "database/schema.generated.graphql"
    extensions:
      graphcool: graphcool.yml
```

if I'm sending request directly to database I'm getting next error:

```
{
  "requestId": "api:api:cjbmbmvz11rsr0168vzjqmmf9",
  "error": "Whoops. Looks like an internal server error. Please contact us from the Console (https://console.graph.cool) or via email (support@graph.cool) and include your Request ID: api:api:cjbmbmvz11rsr0168vzjqmmf9"
}
```

It seems that service endpoint  is wrong:

```
Schema could not be fetched.
Please check if the endpoint 'https://dev.database-beta.graph.cool/api/rcoach-server/dev' is a valid GraphQL Endpoint.
```

after changing graphqlconfig.yaml to

```
projects:
  app:
    ...
  database:
    schemaPath: "database/schema.generated.graphql"
    extensions:
      endpoints:
        default: "https://database-beta.graph.cool/rcoach-server/dev"
```
it finally works

### Expected:

instead of `https://dev.database-beta.graph.cool/api/rcoach-server/dev` is should be `https://database-beta.graph.cool/rcoach-server/dev`

Either boilerplate code is wrong or `graphql-config` library has a bug.
